x-n8n-common: &n8n-common
  build:
    context: .
    dockerfile: Dockerfile
  image: n8n-ffmpeg
  restart: unless-stopped
  volumes:
    - n8n_data:/home/node/.n8n
  environment:
    - TZ=America/Sao_Paulo
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=n8n_postgres
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_DATABASE=n8n_db
    - DB_POSTGRESDB_USER=n8n
    - DB_POSTGRESDB_PASSWORD=n8n_password
    - REDIS_HOST=n8n_redis
    - REDIS_PORT=6379
    - REDIS_PASSWORD=n8n_redis_password
    - REDIS_DB=0
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_HOST=n8n_redis
    - QUEUE_BULL_REDIS_PORT=6379
    - QUEUE_BULL_REDIS_PASSWORD=n8n_redis_password
    - QUEUE_BULL_REDIS_DB=1
    - GENERIC_TIMEZONE=America/Sao_Paulo
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy
  networks:
    - n8n_network

x-n8n-healthcheck: &n8n-healthcheck
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 60s

services:
  postgres:
    image: postgres:17-alpine
    container_name: n8n_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=n8n_db
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n_password
      - TZ=America/Sao_Paulo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d n8n_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - n8n_network

  redis:
    image: redis:7-alpine
    container_name: n8n_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass n8n_redis_password
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - n8n_network

  n8n-main:
    <<: *n8n-common
    container_name: n8n_main
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=MC84Q5zY2dJwn68HZNrwCk
      - N8N_MODE=main
      - EXECUTIONS_PROCESS=main
      - WEBHOOK_TUNNEL_URL=http://n8n-webhook:5678/
      - TZ=America/Sao_Paulo

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz"]
      <<: *n8n-healthcheck

  n8n-webhook:
    <<: *n8n-common
    container_name: n8n_webhook
    ports:
      - "5679:5678"
    environment:
      - N8N_MODE=webhook
      - EXECUTIONS_PROCESS=webhook
      - WEBHOOK_TUNNEL_URL=http://n8n-webhook:5678/
      - WEBHOOK_URL=http://n8n-webhook:5678/
      - N8N_HOST=n8n-webhook
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz"]
      <<: *n8n-healthcheck

  n8n-worker:
    <<: *n8n-common
    container_name: n8n_worker
    environment:
      - N8N_MODE=worker
      - EXECUTIONS_PROCESS=worker
      - WEBHOOK_URL=http://n8n-webhook:5678/
    healthcheck:
      test: ["CMD", "pgrep", "-f", "n8n"]
      <<: *n8n-healthcheck

networks:
  n8n_network:
    driver: bridge

volumes:
  n8n_data:
  postgres_data:
  redis_data: